name = "Typst"
grammar = "typst"
path_suffixes = ["typ"]
line_comments = ["// "]
block_comment = ["/* ", " */"]
autoclose_before = "$"
brackets = [
    { start = "(", end = ")", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "{", end = "}", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "/*", end = "*/", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "*", end = "*", close = true, newline = false },
    { start = "_", end = "_", close = true, newline = false },
    { start = "`", end = "`", close = true, newline = false },
    { start = "$", end = "$", close = true, newline = false },
]